# src/tree_modeling/core/__init__.py

from .types import CrownStats as CrownStats, SkeletonData as SkeletonData
from .constants import (
    BREAST_HEIGHT_M as BREAST_HEIGHT_M,
    TREE_COLORS as TREE_COLORS,
    STEM_ROI_BUFFER_M as STEM_ROI_BUFFER_M,
    CYL_ADDITIONAL_RADIUS_M as CYL_ADDITIONAL_RADIUS_M,
    EDGE_POINTS_DEFAULT as EDGE_POINTS_DEFAULT,
    MIN_GROUND_POINTS as MIN_GROUND_POINTS,
    MIN_Z_AXIS_ALIGNMENT as MIN_Z_AXIS_ALIGNMENT,
)
from .crown import (
    crown_to_mesh as crown_to_mesh,
    crown_diameter as crown_diameter,
    crown_shape as crown_shape,
    crown_height as crown_height,
    crown_base_height as crown_base_height,
    find_lowest_crown_points_by_quadrant as find_lowest_crown_points_by_quadrant,
)
from .stem import (
    fit_cylinder as fit_cylinder,
    calculate_rotation_matrix as calculate_rotation_matrix,
    get_edge_points as get_edge_points,
    generate_cylinder_points as generate_cylinder_points,
    calculate_intersections as calculate_intersections,
    reconstruct_trimesh as reconstruct_trimesh,
    plot_cylinder_with_rays as plot_cylinder_with_rays,
    stem_angle as stem_angle,
    stem_bearing as stem_bearing,
    diameter_at_breastheight as diameter_at_breastheight,
)
from .curation import (
    find_longest_non_nan_sequence as find_longest_non_nan_sequence,
    extract_area_and_points as extract_area_and_points,
    validate_point_density as validate_point_density,
    find_bounds_valid_segments as find_bounds_valid_segments,
    calculate_valid_bbox_area as calculate_valid_bbox_area,
    determine_valid_stem_slices as determine_valid_stem_slices,
    determine_valid_crown_slices as determine_valid_crown_slices,
    mark_invalid_crown_points as mark_invalid_crown_points,
    get_valid_slices as get_valid_slices,
    mark_invalid_stem_points as mark_invalid_stem_points,
    curate_stem_cloud as curate_stem_cloud,
    curate_crown_cloud as curate_crown_cloud,
)
from .skeleton import (
    leafwood_classification as leafwood_classification,
    reconstruct_skeleton as reconstruct_skeleton,
    skeleton_split as skeleton_split,
)
from .graph import (
    build_layered_traversal_levels as build_layered_traversal_levels,
    max_depth_by_level_size as max_depth_by_level_size,
    max_depth_by_cumulative_nodes as max_depth_by_cumulative_nodes,
    bypass_and_remove_nodes as bypass_and_remove_nodes,
    estimate_stem_density as estimate_stem_density,
    remove_isolated_nodes_mode as remove_isolated_nodes_mode,
    remove_artefact_nodes_mode as remove_artefact_nodes_mode,
    filter_skeleton_nodes as filter_skeleton_nodes,
    read_ply as read_ply,
    path_till_split as path_till_split,
    plot_graph_with_path as plot_graph_with_path,
)

__all__ = [
    # types/constants
    "CrownStats",
    "SkeletonData",
    "BREAST_HEIGHT_M",
    "TREE_COLORS",
    "STEM_ROI_BUFFER_M",
    "CYL_ADDITIONAL_RADIUS_M",
    "EDGE_POINTS_DEFAULT",
    "MIN_GROUND_POINTS",
    "MIN_Z_AXIS_ALIGNMENT",
    # crown
    "crown_to_mesh",
    "crown_diameter",
    "crown_shape",
    "crown_height",
    "crown_base_height",
    "find_lowest_crown_points_by_quadrant",
    # stem
    "fit_cylinder",
    "calculate_rotation_matrix",
    "get_edge_points",
    "generate_cylinder_points",
    "calculate_intersections",
    "reconstruct_trimesh",
    "plot_cylinder_with_rays",
    "stem_angle",
    "stem_bearing",
    "diameter_at_breastheight",
    # curation
    "find_longest_non_nan_sequence",
    "extract_area_and_points",
    "validate_point_density",
    "find_bounds_valid_segments",
    "calculate_valid_bbox_area",
    "determine_valid_stem_slices",
    "determine_valid_crown_slices",
    "mark_invalid_crown_points",
    "get_valid_slices",
    "mark_invalid_stem_points",
    "curate_stem_cloud",
    "curate_crown_cloud",
    # skeleton / graph
    "leafwood_classification",
    "reconstruct_skeleton",
    "skeleton_split",
    "build_layered_traversal_levels",
    "max_depth_by_level_size",
    "max_depth_by_cumulative_nodes",
    "bypass_and_remove_nodes",
    "estimate_stem_density",
    "remove_isolated_nodes_mode",
    "remove_artefact_nodes_mode",
    "filter_skeleton_nodes",
    "read_ply",
    "path_till_split",
    "plot_graph_with_path",
]
